//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShadowEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_ShadowEditorTYPE            130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_RESOURCE_VIEW               156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_POPUP_EXPLORER              174
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MAINBAR                     310
#define IDR_RESOURCES                   312
#define IDB_RESOURCES                   316
#define IDR_POPUP_RESOURCES             317
#define IDD_GROUNDEDIT                  318
#define IDD_MAP_PROPS                   321
#define IDD_MESHTEMPLATE                323
#define IDD_NULLEDIT                    324
#define IDD_LISTSEL                     325
#define IDD_LIGHTEDIT                   326
#define IDD_MAT_UVANIM                  327
#define IDD_MAT_TEXANIM                 328
#define IDD_MAT_COLOR                   329
#define IDD_MAT_TEXTURES                331
#define IDD_MAT_STATE                   332
#define IDD_MAT_UV                      333
#define IDD_MAT_FADEANIM                334
#define IDD_PARTICLEEDIT                335
#define IDD_PARTICLEMATERIAL            337
#define IDD_SOUND                       338
#define IDD_GMATERIAL                   339
#define IDC_GROUND_MAT                  1002
#define IDC_GROUND_GMAT                 1003
#define IDC_GROUND_PAINT                1004
#define IDC_GROUND_ERASE                1005
#define IDC_GROUND_REFRESHMATS          1006
#define IDC_GROUND_SPSET                1007
#define IDC_MAT_NAME                    1008
#define IDC_GROUND_WSET                 1008
#define IDC_GROUND_WPOINT               1009
#define IDC_GROUND_WPAINT               1010
#define IDC_MAT_AMBIENTCOL              1011
#define IDC_MAT_DIFFUSECOL              1012
#define IDC_MAT_SPECCOL                 1013
#define IDC_MAT_SHININESS               1020
#define IDC_MAT_SHINESP                 1021
#define IDC_MAT_SINTENSITY              1022
#define IDC_MAT_FADEEND                 1022
#define IDC_MAT_SINTSP                  1023
#define IDC_MAT_FADEENDSP               1023
#define IDC_MAT_DIFFUSET                1024
#define IDC_BMAT_NORMALT                1025
#define IDC_MAT_DIFFUSECK               1026
#define IDC_MAT_NORMALCK                1027
#define IDC_MAT_SPECT                   1028
#define IDC_MAT_SPECCK                  1029
#define IDC_MAT_EMISSIVET               1030
#define IDC_MAT_EMISSIVECK              1031
#define IDC_MAT_UOFF                    1032
#define IDC_MAT_UOFFSP                  1033
#define IDC_MAT_ENVTT                   1034
#define IDC_MAT_ENVTCK                  1035
#define IDC_MAT_USCALE                  1036
#define IDC_USCALESP                    1037
#define IDC_MAT_VOFF                    1038
#define IDC_MAT_VOFFSP                  1039
#define IDC_MAT_VSCALE                  1040
#define IDC_MAT_VSCALESP                1041
#define IDC_MAT_ROT                     1042
#define IDC_MAT_ROTSP                   1043
#define IDC_MAT_ANIMENABLE              1044
#define IDC_MAT_UBOFF                   1045
#define IDC_MAT_UBOFFSP                 1046
#define IDC_MAT_VBOFF                   1047
#define IDC_MAT_VBOFFSP                 1048
#define IDC_MAT_UAOFF                   1049
#define IDC_MAT_UAOFFSP                 1050
#define IDC_MAT_VAOFF                   1051
#define IDC_MAT_VAOFFSP                 1052
#define IDC_MAT_BROT                    1053
#define IDC_MAT_BROTSP                  1054
#define IDC_MAT_AROT                    1055
#define IDC_MAT_AROTSP                  1056
#define IDC_MAT_TTIME                   1057
#define IDC_MAT_ROW                     1058
#define IDC_MAT_COL                     1059
#define IDC_MAT_TEXANIMENABLE           1060
#define IDC_MAT_ALPHA                   1061
#define IDC_MAT_NOSHADOWS               1062
#define IDC_MAT_SRCBLEND                1063
#define IDC_MAT_DESTBLEND               1064
#define IDC_MAT_CULL                    1065
#define IDC_MAT_FCOUNT                  1066
#define IDC_MAP_NAME                    1066
#define IDC_MAP_WIDTH                   1067
#define IDC_MAP_WIDTHSP                 1068
#define IDC_MAP_HEIGHT                  1069
#define IDC_MAP_HEIGHTSP                1070
#define IDC_MAP_SUNENABLE               1071
#define IDC_MAP_AMBIENT                 1072
#define IDC_MAP_SUNCOLOR                1073
#define IDC_MT_GEOMETRY                 1073
#define IDC_MAP_XAXIS                   1074
#define IDC_MT_MAT                      1074
#define IDC_MAP_XAXISSP                 1075
#define IDC_MT_MATEDIT                  1075
#define IDC_MAP_YAXIS                   1076
#define IDC_MT_SHAPE                    1076
#define IDC_MAP_YAXISSP                 1077
#define IDC_MT_NOCOLLISION              1077
#define IDC_MAP_SUNINT                  1078
#define IDC_MT_PREVIEW                  1078
#define IDC_MAP_SUNINTSP                1079
#define IDC_MT_NAME                     1079
#define IDC_SEL_LIST                    1079
#define IDC_MAP_ZAXIS                   1080
#define IDC_LIGHT_COLOR                 1080
#define IDC_MT_GMAT                     1080
#define IDC_MAP_ZAXISSP                 1081
#define IDC_LIGHT_INT                   1081
#define IDC_MT_GMATEDIT                 1081
#define IDC_LIGHT_INTSP                 1082
#define IDC_LIGHT_RANGE                 1083
#define IDC_LIGHT_RANGESP               1084
#define IDC_LIGHT_CASTSHADOWS           1085
#define IDC_LIGHT_SMSIZE                1086
#define IDC_LIGHT_SMFILTER              1087
#define IDC_LIGHT_FAR                   1088
#define IDC_LIGHT_FARSP                 1089
#define IDC_LIGHT_NEAR                  1090
#define IDC_LIGHT_NEARSP                1091
#define IDC_MUV_ENABLE                  1091
#define IDC_LIGHT_DEPTH                 1092
#define IDC_LIGHT_WIDTH                 1093
#define IDC_MUV_OFF                     1093
#define IDC_LIGHT_WIDTHSP               1094
#define IDC_MUV_UOFFSP                  1094
#define IDC_LIGHT_HEIGHT                1095
#define IDC_MUV_VOFF                    1095
#define IDC_LIGHT_HEIGHTSP              1096
#define IDC_MUV_VOFFSP                  1096
#define IDC_LIGHT_DEPTHSP               1097
#define IDC_MUV_ROT                     1097
#define IDC_MUV_ROTSP                   1098
#define IDC_MTEX_ENABLE                 1099
#define IDC_MTEX_TPERROW                1100
#define IDC_MTEX_TPRSP                  1101
#define IDC_MTEX_TPERCOL                1102
#define IDC_MTEX_TPCSP                  1103
#define IDC_MTEX_TCOUNT                 1104
#define IDC_MTEX_TCSP                   1105
#define IDC_MTEX_TIME                   1106
#define IDC_MAT_FADESTART               1106
#define IDC_MAT_FADESTARTSP             1107
#define IDC_MAT_FADEENABLE              1108
#define IDC_PS_PREVIEW                  1109
#define IDC_PS_EMITTERS                 1110
#define IDC_PS_SHOWEMITTER              1111
#define IDC_PS_ADDEMITTER               1112
#define IDC_PS_REMEMITTER               1113
#define IDC_PS_EXPORT                   1141
#define IDC_PS_MATERIAL                 1142
#define IDC_PSM_SINGLE                  1143
#define IDC_PSM_TSET                    1144
#define IDC_PSM_TEX                     1145
#define IDC_PSM_TEXLIST                 1146
#define IDC_PSM_ADD                     1147
#define IDC_PSM_REM                     1148
#define IDC_PSM_UP                      1149
#define IDC_PSM_DOWN                    1150
#define IDC_PSM_BLEND                   1151
#define IDC_PSM_SRC                     1153
#define IDC_PSM_DEST                    1154
#define IDC_SND_NAME                    1154
#define IDC_SND_FILE                    1155
#define IDC_SND_PRIOR                   1156
#define IDC_SND_PRIORSP                 1157
#define IDC_SND_RADIUS                  1158
#define IDC_SND_RADIUSSP                1159
#define IDC_SND_RANGLE                  1160
#define IDC_SND_RANGLESP                1161
#define IDC_SND_CONE                    1162
#define IDC_SND_IANGLE                  1163
#define IDC_SND_IANGLESP                1164
#define IDC_SND_OANGLE                  1165
#define IDC_SND_OANGLESP                1166
#define IDC_SND_IVOL                    1167
#define IDC_SND_IVOLSP                  1168
#define IDC_SND_OVOL                    1169
#define IDC_SND_OVOLSP                  1170
#define IDC_SND_ILPF                    1171
#define IDC_SND_ILPFSP                  1172
#define IDC_SND_OLPF                    1173
#define IDC_SND_OLPFSP                  1174
#define IDC_SND_IREV                    1175
#define IDC_SND_IREVSP                  1176
#define IDC_SND_OREV                    1177
#define IDC_SND_OREVSP                  1178
#define IDC_SND_PLAY                    1179
#define IDC_GMAT_NAME                   1180
#define IDC_GMAT_DEBRIS                 1181
#define ID_FILE_COPY                    32771
#define ID_FILE_PASTE                   32773
#define ID_FILE_DELETE                  32774
#define ID_TOOL_UNDO                    32775
#define ID_TOOL_REDO                    32776
#define ID_TOOL_SELECT                  32777
#define ID_TOOL_CAMTRANSLATE            32778
#define ID_TOOL_CAMROTATE               32779
#define ID_TOOL_TRANSLATE               32780
#define ID_TOOL_ROTATE                  32781
#define ID_TOOL_LOCKX                   32782
#define ID_TOOL_LOCKZ                   32784
#define ID_TOOL_LOCKY                   32785
#define ID_TOOL_ALIGN                   32786
#define ID_TOOL_FALL2                   32787
#define ID_EDIT_REDO32788               32788
#define ID_EDIT_DELETE                  32789
#define ID_TOOLS_SELECTION              32790
#define ID_TOOLS_TRANSLATECAMERA        32791
#define ID_TOOLS_ROTATECAMERA           32792
#define ID_TOOLS_TRANSLATEOBJECT        32793
#define ID_TOOLS_ROTATEOBJECT           32794
#define ID_TOOLS_LOCKX                  32795
#define ID_TOOLS_LOCKY                  32796
#define ID_TOOLS_LOCKZ                  32797
#define ID_TOOLS_ALIGNOBJECT            32798
#define ID_TOOLS_FALLOBJECT             32799
#define ID_RES_NEW                      32800
#define ID_RES_OPEN                     32801
#define ID_RES_EDIT                     32802
#define ID_RESOURCES_NEW                32803
#define ID_RESOURCES_OPEN               32804
#define ID_RESOURCES_EDIT               32805
#define ID_FILE_SAVE2                   32806
#define ID_EDIT_MAPPROPERTIES           32807
#define ID_CREATE_MESH                  32808
#define ID_TOOLS_SNAP                   32809
#define ID_TOOLS_HEIGHT                 32810
#define ID_CREATE_LIGHT                 32811
#define ID_LIGHT_OMNI                   32812
#define ID_LIGHT_SPOT                   32813
#define ID_LIGHT_AREA                   32814
#define ID_CREATE_LIGHT_OMNI            32815
#define ID_CREATE_LIGHT_SPOT            32816
#define ID_CREATE_LIGHT_AREA            32817
#define ID_TOOLS_ROTATEZ                32818
#define ID_EDIT_COPY2                   32819
#define ID_EDIT_PASTE2                  32820
#define ID_TEST                         32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
